//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.SampleXmlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleXmlService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verifyXml", ReplyAction="http://tempuri.org/IService1/verifyXmlResponse")]
        string verifyXml(string xsdUrl, string xmlUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verifyXml", ReplyAction="http://tempuri.org/IService1/verifyXmlResponse")]
        System.Threading.Tasks.Task<string> verifyXmlAsync(string xsdUrl, string xmlUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchByTagName", ReplyAction="http://tempuri.org/IService1/searchByTagNameResponse")]
        string[] searchByTagName(string xmlUrl, string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchByTagName", ReplyAction="http://tempuri.org/IService1/searchByTagNameResponse")]
        System.Threading.Tasks.Task<string[]> searchByTagNameAsync(string xmlUrl, string tagName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryIt.SampleXmlService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryIt.SampleXmlService.IService1>, TryIt.SampleXmlService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string verifyXml(string xsdUrl, string xmlUrl) {
            return base.Channel.verifyXml(xsdUrl, xmlUrl);
        }
        
        public System.Threading.Tasks.Task<string> verifyXmlAsync(string xsdUrl, string xmlUrl) {
            return base.Channel.verifyXmlAsync(xsdUrl, xmlUrl);
        }
        
        public string[] searchByTagName(string xmlUrl, string tagName) {
            return base.Channel.searchByTagName(xmlUrl, tagName);
        }
        
        public System.Threading.Tasks.Task<string[]> searchByTagNameAsync(string xmlUrl, string tagName) {
            return base.Channel.searchByTagNameAsync(xmlUrl, tagName);
        }
    }
}
